### ISSUE TITLE
Mirror pro repo

### ISSUE THREAD

**Issue by dmarkwat** [maxpoint/conda-mirror#24]
I'm imagining lots of reasons why this might be inadvisable, but is there a way (or reasons why not to) mirror the [Anaconda "pro" repository](https://repo.continuum.io/pkgs/pro/)?  Seems the ["free" repository](https://repo.continuum.io/pkgs/free/) is the [only one to mirror when referring to the 'defaults' or 'anaconda' repo](https://github.com/maxpoint/conda-mirror/blob/master/conda_mirror/conda_mirror.py#L374), but when I look at anaconda.org and search for a package under "pro" (e.g. [accelerate](https://repo.continuum.io/pkgs/pro/linux-64/accelerate-2.3.0-np19py27_3.tar.bz2)) it appears as being [under the "anaconda" owner](https://anaconda.org/anaconda/accelerate).  Recommendations or thoughts to work around this?

**Comment by ericdill** [comment]
@dmarkwat It is not a technical challenge to update `conda-mirror` to do this. 

I have no information regarding the legality of mirroring the pro repo (i am not a lawyer).  

I am going to start having to mirror the `r` channel internally as we are starting to get some requests for r packages. The proposed update (PR incoming shortly) will allow you to pass in the fully qualified channel `--upstream-channel https://repo.continuum.io/pkgs/r` instead of just a channel (like `--upstream-channel conda-forge`.  Incidentally this will allow you to mirror the pro channel if you so choose.

**Comment by dmarkwat** [comment]
Sounds great!  That would work perfectly for the automation I'm setting up around this.  Looking forward to the PR.

**Comment by ericdill** [comment]
closed by #25
